name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run
 
    - name: Build C# code
      run: dotnet build

    - name: Run C# dotnet test
      run: dotnet test

    - name: Install Dependencies
      working-directory: ./DotnetTemplate.Web
      run: npm install

    - name: Build NPM Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm run build

    - name: Run linter on Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Test typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm t

    - name: Check Status Step - Success
      id: check-step-success
      if: success()
      shell: bash
      run:
        echo "Workflow Successful."

    - name: Check Status Step - Failure
      id: check-step-Failure
      if: failure()
      shell: bash
      run:
        echo "Workflow failure."

  